# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenfra < Formula
  desc "Estimate the environmental impact of your infrastructure change within your Terraform projects!"
  homepage "https://github.com/Donovan1905/Greenfra"
  version "0.2.0"

  depends_on "elvish" => :optional
  depends_on "fish" => "v1.2.3"
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.2.0/Greenfra_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "d20723fb04cfb6ead6aa9041b89a93eec0aa990276e693468168fc09b36cd5b2"

      def install
        bin.install "Greenfra"
      end
    end
    on_arm do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.2.0/Greenfra_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "d15cc0e209dbc7fb4734438cebb60c941401728de72cac1b5a404cf2ed3ecf11"

      def install
        bin.install "Greenfra"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.2.0/Greenfra_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "14e1b25e298e990f7c6e79b83c5a90cc7df3391323ca09db359544801e74b42c"

        def install
          bin.install "Greenfra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.2.0/Greenfra_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "1eef5e4df2bf600a13acc7903e0cb3c9444dc221d27b27ff53a41f51584d33ce"

        def install
          bin.install "Greenfra"
        end
      end
    end
  end

  conflicts_with "svn"
  conflicts_with "bash"
end
