# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenfra < Formula
  desc "Estimate the environmental impact of your infrastructure change within your Terraform projects!"
  homepage "https://github.com/Donovan1905/Greenfra"
  version "0.3.0"

  depends_on "elvish" => :optional
  depends_on "fish" => "v1.2.3"
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.3.0/Greenfra_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3ccd231eb7b60daa5ce16001f7c73c25f0dee5c9ff6633927c6a7c2c5f378ab8"

      def install
        bin.install "Greenfra"
      end
    end
    on_arm do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.3.0/Greenfra_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "01b2ba2ff3645b29a78833dbe162dfe96eebd50ae78026f72f8a57a35bbabf6e"

      def install
        bin.install "Greenfra"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.3.0/Greenfra_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "e7e548d9977f8f3806ddfd6d6e6c4fc77176b2d4c934bc33c99c2b9b0780155f"

        def install
          bin.install "Greenfra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.3.0/Greenfra_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "4bf1106a60b225975247dc2f912815f180b23655a7ba2b2548040d63cdd5b6ed"

        def install
          bin.install "Greenfra"
        end
      end
    end
  end

  conflicts_with "svn"
  conflicts_with "bash"
end
