# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greenfra < Formula
  desc "Estimate the environmental impact of your infrastructure change within your Terraform projects!"
  homepage "https://github.com/Donovan1905/Greenfra"
  version "0.1.0"

  depends_on "elvish" => :optional
  depends_on "fish" => "v1.2.3"
  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.1.0/Greenfra_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "eb29ca2f4903c54019bfbd5fc204b07fbaec4e65e4ce55430753f8248686a519"

      def install
        bin.install "Greenfra"
      end
    end
    on_arm do
      url "https://github.com/Donovan1905/greenfra/releases/download/v0.1.0/Greenfra_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b416f52ec129d204e194d21204c6ad763eff9e6e2a0bd66290ac1310c62ea84e"

      def install
        bin.install "Greenfra"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.1.0/Greenfra_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "f9132a941cddad2fa4423f88161ce4c9a42e78e4da11399f033cb1a7f194c204"

        def install
          bin.install "Greenfra"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Donovan1905/greenfra/releases/download/v0.1.0/Greenfra_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "e1f74a2229f489882d949c297b31f577d5ea04cdbad7a33b09f0b1c3acd34749"

        def install
          bin.install "Greenfra"
        end
      end
    end
  end

  conflicts_with "svn"
  conflicts_with "bash"
end
